{
 "title": "Charging",
 "time": { "from": "now/w", "to": "now/w" },
 "templating": {
  "list": [
   {
    "name": "group_name",
    "label": "Park name",
    "query": "SELECT DISTINCT group_name\nFROM default.sensors\nWHERE type = 'charging_station'\nand group_name is not null"
   }
  ]
 },
 "panels": [
  {
   "title": "Real time status",
   "type": "orchestracities-map-panel",
   "gridPos": { "h": 11, "w": 20, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT latitude, longitude, sensor_name, not argMax(is_occupied, timestamp) as status\nfrom sensors.charging_station\nwhere group_name = '${group_name}' and timestamp <= now()\ngroup by latitude, longitude, sensor_name\n"
    }
   ]
  },
  {
   "title": "Real time occupancy rate",
   "type": "piechart",
   "gridPos": { "h": 13, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "rawSql": "select countIf(occupied) as occupied, count(*) as total, (total - occupied) as free\nfrom (\n         SELECT sensor_name,\n                argMax(is_occupied, timestamp) as occupied\n         FROM sensors.charging_station\n         where group_name = '${group_name}' and timestamp <= now()\n         group by sensor_name\n         );"
    }
   ]
  },
  {
   "title": "Total occupancy time by charging station",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 13, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "with sequences as (SELECT sensor_name,\n                          group_name,\n                          timestamp,\n                          is_occupied,\n                          if(neighbor(sensor_uuid, 1, NULL) != sensor_uuid, NULL,\n                             neighbor(timestamp, 1, NULL))            as next_timestamp,\n                          dateDiff('seconds', timestamp, next_timestamp) as seconds\n                   FROM sensors.charging_station)\nselect\n    sumIf(seconds, is_occupied = 1) as occupied_seconds,\n    dateDiff('seconds', $__fromTime, $__toTime) as max_time,\n    sensor_name\nfrom sequences\nwhere group_name = '${group_name}'\nand timestamp >= $__fromTime and timestamp <= $__toTime\ngroup by sensor_name\norder by occupied_seconds desc\n"
    }
   ]
  }
 ]
}