{
 "title": "TEST",
 "time": { "from": "2023-01-01T00:00:00.000Z", "to": "2023-11-08T11:00:00.000Z" },
 "panels": [
  {
   "title": "Panel Title",
   "type": "geomap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "database": "sensors",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT \n      latitude,\n      longitude\nFROM sensors.temperature\n\n",
     "query": "SELECT \n      longitude AS lon,\n      latitude  AS lat\nFROM sensors.traffic\n\n",
     "rawQuery": "SELECT \n      longitude AS lon,\n      latitude  AS lat\nFROM sensors.traffic",
     "round": "0s",
     "table": "temperature"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "database": "sensors",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT timestamp as time, value as Temperature FROM sensors.temperature",
     "rawQuery": "SELECT timestamp as time, value as Temperature FROM sensors.temperature",
     "round": "0s",
     "table": "traffic"
    }
   ]
  },
  {
   "title": "Vehicles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "database": "sensors",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT timestamp as time, vehicles_per_hour as Vehicles FROM sensors.traffic",
     "rawQuery": "SELECT timestamp as time, vehicles_per_hour as Vehicles FROM sensors.traffic",
     "round": "0s",
     "table": "traffic"
    }
   ]
  },
  {
   "title": "Monthly mean temperature",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT\n    toDate(timestamp) AS date,\n    avg(value) AS mean_daily_temperature\nFROM sensors.temperature\nGROUP BY date\nORDER BY date",
     "query": "SELECT\n    toMonth(timestamp) AS month,\n    avg(value) AS monthly_mean_temperature\nFROM sensors.temperature\nGROUP BY month\nORDER BY month",
     "rawQuery": "SELECT\n    toMonth(timestamp) AS month,\n    avg(value) AS monthly_mean_temperature\nFROM sensors.temperature\nGROUP BY month\nORDER BY month",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Monthly mean cars",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT timestamp as time, vehicles_per_hour as Vehicles FROM sensors.traffic",
     "query": "SELECT\n    toMonth(timestamp) AS month,\n    avg(vehicles_per_hour) AS monthly_mean_cars\nFROM sensors.traffic\nGROUP BY month\nORDER BY month",
     "rawQuery": "SELECT\n    toMonth(timestamp) AS month,\n    avg(vehicles_per_hour) AS monthly_mean_cars\nFROM sensors.traffic\nGROUP BY month\nORDER BY month",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Daily mean temperature",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "database": "sensors",
     "dateColDataType": " ",
     "dateTimeColDataType": "timestamp",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    toDate(timestamp) AS date,\n    avg(value) AS daily_mean_temperature\nFROM sensors.temperature\nGROUP BY date\nORDER BY date\n",
     "rawQuery": "SELECT\n    toDate(timestamp) AS date,\n    avg(value) AS daily_mean_temperature\nFROM sensors.temperature\nGROUP BY date\nORDER BY date",
     "round": "0s",
     "table": "temperature"
    }
   ]
  }
 ]
}