{
 "title": "Dati urbanistici",
 "time": { "from": "now-2y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "group_name",
    "label": "Park name charging",
    "query": "SELECT DISTINCT group_name\nFROM default.sensors\nWHERE type = 'charging_station'\nand group_name is not null"
   },
   {
    "name": "group_name_parking",
    "label": "Park name parking",
    "query": "SELECT DISTINCT group_name\nFROM default.sensors\nWHERE type = 'parking'\nand group_name is not null"
   },
   {
    "name": "Sensor_name_recycling_point",
    "label": "Sensor name recycling_point",
    "query": "SELECT DISTINCT sensor_name\nFROM sensors.recycling_point\nORDER BY sensor_name"
   },
   {
    "name": "Sensor_name_traffic",
    "label": "Sensor name traffic",
    "query": "SELECT DISTINCT sensor_name\nFROM sensors.traffic\nORDER BY sensor_name"
   }
  ]
 },
 "panels": [
  {
   "title": "Charging",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Real time status",
     "type": "orchestracities-map-panel",
     "gridPos": { "h": 11, "w": 20, "x": 0, "y": 113 },
     "targets": [
      {
       "rawSql": "SELECT latitude, longitude, sensor_name, argMax(kwh_supplied, timestamp) > 0 as status\nfrom sensors.charging_station\nwhere group_name = '${group_name}' and timestamp <= now()\ngroup by latitude, longitude, sensor_name\n"
      }
     ]
    },
    {
     "title": "Real time occupancy rate",
     "type": "piechart",
     "gridPos": { "h": 13, "w": 4, "x": 20, "y": 113 },
     "targets": [
      {
       "rawSql": "select countIf(occupied) as occupied, count(*) as total, (total - occupied) as free\nfrom (\n         SELECT sensor_name,\n                argMax(kwh_supplied, timestamp) = 0 as occupied\n         FROM sensors.charging_station\n         where group_name = '${group_name}' and timestamp <= now()\n         group by sensor_name\n         );"
      }
     ]
    },
    {
     "title": "Total occupancy time by charging station",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 13, "x": 0, "y": 124 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "rawSql": "with sequences as (SELECT sensor_name,\n                          group_name,\n                          timestamp,\n                          kwh_supplied,\n                          if(neighbor(sensor_uuid, 1, NULL) != sensor_uuid, NULL,\n                             neighbor(timestamp, 1, NULL))            as next_timestamp,\n                          dateDiff('seconds', timestamp, next_timestamp) as seconds\n                   FROM sensors.charging_station)\nselect\n    sumIf(seconds, kwh_supplied > 0) as occupied_seconds,\n    dateDiff('seconds', $__fromTime, $__toTime) as max_time,\n    sensor_name\nfrom sequences\nwhere group_name = '${group_name}'\nand timestamp >= $__fromTime and timestamp <= $__toTime\ngroup by sensor_name\norder by occupied_seconds desc\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Parking",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Real time status",
     "type": "orchestracities-map-panel",
     "gridPos": { "h": 11, "w": 20, "x": 0, "y": 90 },
     "targets": [
      {
       "rawSql": "SELECT latitude, longitude, sensor_name, not argMax(is_occupied, timestamp) as status\nfrom sensors.parking\nwhere group_name = '${group_name}' and timestamp <= now()\ngroup by latitude, longitude, sensor_name\n"
      }
     ]
    },
    {
     "title": "Real time occupancy rate",
     "type": "piechart",
     "gridPos": { "h": 13, "w": 4, "x": 20, "y": 90 },
     "targets": [
      {
       "rawSql": "select countIf(occupied) as occupied, count(*) as total, (total - occupied) as free\nfrom (\n         SELECT sensor_name,\n                argMax(is_occupied, timestamp) as occupied\n         FROM sensors.parking\n         where group_name = '${group_name}' and timestamp <= now()\n         group by sensor_name\n         );"
      }
     ]
    },
    {
     "title": "Total occupancy time by parking lot",
     "type": "bargauge",
     "gridPos": { "h": 12, "w": 13, "x": 0, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "rawSql": "with sequences as (SELECT sensor_name,\n                          group_name,\n                          timestamp,\n                          is_occupied,\n                          if(neighbor(sensor_uuid, 1, NULL) != sensor_uuid, NULL,\n                             neighbor(timestamp, 1, NULL))            as next_timestamp,\n                          dateDiff('seconds', timestamp, next_timestamp) as seconds\n                   FROM sensors.parking)\nselect\n    sumIf(seconds, is_occupied = 1) as occupied_seconds,\n    dateDiff('seconds', $__fromTime, $__toTime) as max_time,\n    sensor_name\nfrom sequences\nwhere group_name = '${group_name}'\nand timestamp >= $__fromTime and timestamp <= $__toTime\ngroup by sensor_name\norder by occupied_seconds desc\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Recycling Point",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Location",
     "type": "geomap",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 43 },
     "targets": [
      {
       "rawSql": "SELECT sensor_name,\n       'Recycling Point' as type,\n       latitude,\n       longitude\nFROM sensors.recycling_point\nwhere sensor_name = '${sensor_name}'\nGROUP BY sensor_name, latitude, longitude"
      }
     ]
    },
    {
     "title": "History of filling and discharge",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 19, "x": 0, "y": 52 },
     "targets": [
      {
       "rawSql": "select timestamp, filling\nfrom sensors.recycling_point\nwhere timestamp >= $__fromTime and timestamp <= $__toTime\nand sensor_name = '${sensor_name}'\norder by timestamp;"
      }
     ]
    },
    {
     "title": "Real time filling",
     "type": "stat",
     "gridPos": { "h": 10, "w": 5, "x": 19, "y": 52 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT filling\r\nFROM sensors.recycling_point\r\nWHERE timestamp <= now()\r\nAND sensor_name = '${sensor_name}'\r\nORDER BY timestamp DESC\r\nLIMIT 1"
      }
     ]
    },
    {
     "title": "Total saturation",
     "type": "gauge",
     "description": "This panel shows the cumulative hours that the recycling point has reached its full capacity, rendering it unusable, over a selected period of time.",
     "gridPos": { "h": 8, "w": 5, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "rawSql": "with sequences as (\n    SELECT sensor_name,\n           timestamp,\n           if(neighbor(sensor_uuid, 1, NULL) != sensor_uuid, NULL,\n              neighbor(timestamp, 1, NULL))     as next_timestamp,\n           if(neighbor(sensor_uuid, 1, NULL) != sensor_uuid, NULL,\n              neighbor(filling, 1, NULL)) as next_filling,\n           if(next_filling == 100 and filling == 100, 1, 0) as saturated\n    FROM sensors.recycling_point\n    where timestamp > $__fromTime and timestamp < $__toTime\n),\ngrouped as (\n    select sensor_name,\n           sum(if(saturated = 1, dateDiff('seconds', timestamp, next_timestamp), 0)) as total_seconds\n    from sequences\n    group by sensor_name\n)\nselect *\nfrom grouped\nwhere sensor_name = '${sensor_name}';\n"
      }
     ]
    },
    {
     "title": "Discharge Efficiency Index (DEI)",
     "type": "gauge",
     "description": "Index from 0 to 10 which represent how efficient is the discharge of the selected recycling point. The longer the recycling point stays full without being emptied, the lower the index is and viceversa.",
     "gridPos": { "h": 8, "w": 5, "x": 5, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "SELECT avg(if(neighbor(sensor_uuid, -1, NULL) != sensor_uuid, NULL, neighbor(filling, -1, NULL)) AS previous_filling) as avg_filling\nFROM sensors.recycling_point\nwhere filling < previous_filling\nand sensor_name = '${sensor_name}'\nand timestamp > $__fromTime and timestamp < $__toTime"
      }
     ]
    },
    {
     "title": "Filling level percentages by range",
     "type": "barchart",
     "description": "This panel shows the percentage distribution of filling values for the sensor, categorized into three ranges: less than 50% (Low level), from 50% to 80% (Moderate level), more than 80% (High level).",
     "gridPos": { "h": 8, "w": 14, "x": 10, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "rawSql": "SELECT\n    range,\n    (count(*) * 100.0 / total_count) AS percentage,\n    CASE\n        WHEN range = 'High level' THEN 1\n        WHEN range = 'Moderate level' THEN 2\n        WHEN range = 'Low level' THEN 3\n    END AS sort_order\nFROM (\n    SELECT\n        'Low level' AS range,\n        filling\n    FROM sensors.recycling_point\n    WHERE sensor_name = '${sensor_name}' AND filling <= 50\n    and timestamp >= $__fromTime and timestamp <= $__toTime\n    \n    UNION ALL\n\n    SELECT\n        'Moderate level' AS range,\n        filling\n    FROM sensors.recycling_point\n    WHERE sensor_name = '${sensor_name}' AND filling > 50 AND filling <= 80\n    and timestamp >= $__fromTime and timestamp <= $__toTime\n    \n    UNION ALL\n\n    SELECT\n        'High level' AS range,\n        filling\n    FROM sensors.recycling_point\n    WHERE sensor_name = '${sensor_name}' AND filling > 80\n    and timestamp >= $__fromTime and timestamp <= $__toTime\n\n) AS ranges\nCROSS JOIN (\n    SELECT count(*) AS total_count\n    FROM sensors.recycling_point\n    WHERE sensor_name = '${sensor_name}'\n    and timestamp >= $__fromTime and timestamp <= $__toTime\n) AS total\nGROUP BY range, total_count\nORDER BY sort_order;\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Location",
     "type": "geomap",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
     "targets": [
      {
       "rawSql": "SELECT sensor_name,\n       'Traffic' as type,\n       latitude,\n       longitude\nFROM sensors.traffic\nwhere sensor_name = '${sensor_name}'\nGROUP BY sensor_name, latitude, longitude\n\n"
      }
     ]
    },
    {
     "title": "Vehicles",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 13 },
     "targets": [
      {
       "rawSql": "select date, argMax(vehicles, insertion_timestamp) as vehicles\nfrom sensors.traffic_1h\nwhere sensor_name = '${sensor_name}' and date >= $__fromTime and date <= $__toTime\ngroup by date\norder by date\n"
      }
     ]
    },
    {
     "title": "Real time",
     "type": "gauge",
     "gridPos": { "h": 11, "w": 10, "x": 0, "y": 24 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT vehicles, avg_speed as speed\nFROM sensors.traffic\nWHERE sensor_name = '${sensor_name}'\nORDER BY timestamp desc\nLIMIT 1\n"
      }
     ]
    },
    {
     "title": "Avg speed",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 14, "x": 10, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
     "targets": [
      {
       "rawSql": "select date, argMax(speed, insertion_timestamp) as speed\nfrom sensors.traffic_1h\nwhere sensor_name = '${sensor_name}' and date >= $__fromTime and date <= $__toTime\ngroup by date\norder by date\n"
      }
     ]
    },
    {
     "title": "Avg vehicles per hour",
     "type": "barchart",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
     "targets": [
      {
       "rawSql": "select toHour(date) as hour, argMax(vehicles, insertion_timestamp) as vehicles\nfrom sensors.traffic_1h\nwhere sensor_name = '${sensor_name}'\nand date >= $__fromTime and date <= $__toTime\ngroup by hour\norder by hour;\n"
      }
     ]
    }
   ]
  }
 ]
}