{
 "title": "Ecological_island",
 "time": { "from": "2024-05-17T22:00:00.000Z", "to": "2024-05-25T21:59:59.000Z" },
 "templating": {
  "list": [
   {
    "name": "sensor_name",
    "label": "Sensor name",
    "query": "SELECT DISTINCT sensor_name\nFROM sensors.ecological_island\nORDER BY sensor_name"
   }
  ]
 },
 "panels": [
  {
   "title": "Location",
   "type": "geomap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT sensor_name,\n       'Ecological island' as type,\n       latitude,\n       longitude\nFROM sensors.ecological_island\nGROUP BY sensor_name, latitude, longitude\n\n\n"
    }
   ]
  },
  {
   "title": "History of filling and discharge",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT \n  timestamp as time, \n  filling_value \nFROM sensors.ecological_island\nwhere timestamp  >= $__fromTime AND timestamp <= $__toTime \nand sensor_name = '${sensor_name}'"
    }
   ]
  },
  {
   "title": "Real time filling",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT filling_value\r\nFROM sensors.ecological_island\r\nWHERE timestamp <= now()\r\nAND sensor_name = '${sensor_name}'\r\nORDER BY timestamp DESC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "maximum saturation hours",
   "type": "gauge",
   "description": "This panel shows the cumulative hours that the ecological island has reached its full capacity, rendering it unusable, over a selected period of time.",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT count(*)\nFROM sensors.ecological_island\nWHERE sensor_name = '${sensor_name}' AND filling_value = 100 AND timestamp  >= $__fromTime AND timestamp <= $__toTime"
    }
   ]
  },
  {
   "title": "filling level percentages by range",
   "type": "barchart",
   "description": "This panel shows the percentage distribution of filling values for the sensor, categorized into three ranges: less than 50% (Low level), from 50% to 80% (Moderate level), more than 80% (High level).",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n    range,\n    (count(*) * 100.0 / total_count) AS percentage,\n    CASE\n        WHEN range = 'High level' THEN 1\n        WHEN range = 'Moderate level' THEN 2\n        WHEN range = 'Low level' THEN 3\n    END AS sort_order\nFROM (\n    SELECT\n        'Low level' AS range,\n        filling_value\n    FROM sensors.ecological_island\n    WHERE sensor_name = '${sensor_name}' AND filling_value <= 50\n\n    UNION ALL\n\n    SELECT\n        'Moderate level' AS range,\n        filling_value\n    FROM sensors.ecological_island\n    WHERE sensor_name = '${sensor_name}' AND filling_value > 50 AND filling_value <= 80\n\n    UNION ALL\n\n    SELECT\n        'High level' AS range,\n        filling_value\n    FROM sensors.ecological_island\n    WHERE sensor_name = '${sensor_name}' AND filling_value > 80\n) AS ranges\nCROSS JOIN (\n    SELECT count(*) AS total_count\n    FROM sensors.ecological_island\n    WHERE sensor_name = '${sensor_name}'\n) AS total\nGROUP BY range, total_count\nORDER BY sort_order;\n"
    }
   ]
  }
 ]
}