{
 "title": "Environmental Data",
 "time": { "from": "2024-07-03T06:05:15.876Z", "to": "2024-07-03T09:27:03.279Z" },
 "templating": {
  "list": [
   {
    "name": "group_name",
    "label": "Temperature",
    "query": "select distinct group_name\nfrom sensors.temperature\n"
   },
   {
    "name": "sensor_name",
    "label": "Humidity",
    "query": "SELECT DISTINCT sensor_name\nFROM sensors.humidity\nORDER BY sensor_name"
   },
   {
    "name": "sensor_name_precipitation",
    "label": "Precipitation",
    "query": "SELECT DISTINCT sensor_name\nFROM sensors.precipitation\nORDER BY sensor_name"
   },
   {
    "name": "sensor_name_river_level",
    "label": "River Level",
    "query": "SELECT DISTINCT sensor_name\nFROM sensors.river_level\nORDER BY sensor_name"
   },
   {
    "name": "sensor_name_air_quality",
    "label": "Air Quality",
    "query": "SELECT DISTINCT sensor_name\nFROM sensors.air_quality"
   }
  ]
 },
 "panels": [
  {
   "title": "Temperature",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Real time temperature",
     "type": "orchestracities-map-panel",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "rawSql": "SELECT center_of_mass_latitude,\n       center_of_mass_longitude,\n       sensor_name,\n       latitude,\n       longitude,\n       (20 * radius_in_km + 10) as radius,\n       avg(heat_index)          as avg_heat_index,\n       avg(avg_humidity)        as avg_humidity,\n       argMax(value, timestamp) as actual_temperature\nFROM sensors.heat_index hi\n         join sensors.temperature t on t.group_name = hi.group_name\nWHERE group_name = '${group_name}' and timestamp <= now() \nGROUP BY center_of_mass_latitude, center_of_mass_longitude, radius_in_km, sensor_name, latitude, longitude\n"
      }
     ]
    },
    {
     "title": "Current Year Livability Temperature Index (LTI)",
     "type": "gauge",
     "description": "The Livability Temperature Index (LTI) is a scale from 0 to 10 that represents how comfortable a city's climate is based on temperature. The index considers the average annual temperature and their suitability for comfortable living",
     "gridPos": { "h": 12, "w": 8, "x": 0, "y": 12 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "with daily_averages as(\n    SELECT\n        date,\n        argMax(avg_temperature, insertion_timestamp) AS daily_avg,\n        max(insertion_timestamp) AS last_insertion_time FROM sensors.temperature_daily\n    WHERE date > toStartOfYear(now()) and date < toStartOfYear(now() + interval '1' year)\n    AND group_name = '$group_name'\n    GROUP BY date\n    ORDER BY date\n)\nselect\n    countIf(daily_avg >= 15 AND daily_avg <= 25) as CS_days_in_range,\n    countIf(daily_avg > 35) + countIf(daily_avg < 5) as ETP_days_out_of_range,\n    stddevPop(daily_avg) as VP_std_dev,\n    (avg(daily_avg) - 15) / (25 - 15) * 100 as OATS,\n    count() as total_days,\n    greatest(0, round((2 * CS_days_in_range - ETP_days_out_of_range - VP_std_dev + OATS) / 4)) as comfort_score\nfrom daily_averages;\n"
      }
     ]
    },
    {
     "title": "Time series",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 15, "x": 9, "y": 12 },
     "targets": [
      {
       "rawSql": "SELECT timestamp, heat_index, avg_temperature\nFROM sensors.heat_index\nWHERE timestamp >= $__fromTime AND timestamp <= $__toTime AND group_name = '${group_name}'\nORDER BY timestamp;"
      }
     ]
    },
    {
     "title": "Daily average",
     "type": "barchart",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 24 },
     "targets": [
      {
       "rawSql": "SELECT\n    date,\n    argMax(avg_temperature, insertion_timestamp) AS Temperature\nFROM sensors.temperature_5m\nWHERE date >= $__fromTime AND date <= $__toTime AND group_name = '${group_name}'\nGROUP BY date\nORDER BY date\nLIMIT 30;\n"
      }
     ]
    },
    {
     "title": "Weekly average",
     "type": "barchart",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT\n    toDate(timestamp) AS date,\n    avg(value) AS mean_daily_temperature\nFROM sensors.temperature\nGROUP BY date\nORDER BY date",
       "query": "SELECT\n    toMonth(timestamp) AS month,\n    avg(value) AS monthly_mean_temperature\nFROM sensors.temperature\nGROUP BY month\nORDER BY month",
       "rawQuery": "SELECT\n    toMonth(timestamp) AS month,\n    avg(value) AS monthly_mean_temperature\nFROM sensors.temperature\nGROUP BY month\nORDER BY month",
       "rawSql": "SELECT\n    date,\n    argMax(avg_temperature, insertion_timestamp) AS Temperature\nFROM sensors.temperature_weekly\nWHERE date >= $__fromTime AND date <= $__toTime AND group_name = '${group_name}'\nGROUP BY date\nORDER BY date",
       "round": "0s"
      }
     ]
    },
    {
     "title": "Min, max and average",
     "type": "gauge",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "database": "sensors",
       "dateColDataType": " ",
       "dateTimeColDataType": "timestamp",
       "dateTimeType": "DATETIME64",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n    toDate(timestamp) AS date,\n    avg(value) AS daily_mean_temperature\nFROM sensors.temperature\nGROUP BY date\nORDER BY date\n",
       "rawQuery": "SELECT\n    toDate(timestamp) AS date,\n    avg(value) AS daily_mean_temperature\nFROM sensors.temperature\nGROUP BY date\nORDER BY date",
       "rawSql": "SELECT\n    min(value) as min_temperature,\n    avg(value) AS avg_temperature,\n    max(value) as max_temperature\nFROM sensors.temperature\nwhere group_name = '${group_name}' and timestamp  >= $__fromTime AND timestamp <= $__toTime\n\n",
       "round": "0s"
      }
     ]
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Location",
     "type": "geomap",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "rawSql": "SELECT distinct sensor_name,\n       'Humidity' as type,\n       latitude,\n       longitude\nFROM sensors.humidity\nWHERE sensor_name = '${sensor_name}'\n"
      }
     ]
    },
    {
     "title": "Daily average",
     "type": "barchart",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "rawSql": "SELECT\n    date,\n    argMax(avg_humidity, insertion_timestamp) AS Humidity\nFROM sensors.humidity_5m\nWHERE date >= $__fromTime AND date <= $__toTime AND sensor_name = '${sensor_name}'\nGROUP BY date\nORDER BY date\nLIMIT 30;\n"
      }
     ]
    },
    {
     "title": "Weekly average",
     "type": "barchart",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT\n    toDate(timestamp) AS date,\n    avg(value) AS mean_daily_temperature\nFROM sensors.temperature\nGROUP BY date\nORDER BY date",
       "query": "SELECT\n    toMonth(timestamp) AS month,\n    avg(value) AS monthly_mean_temperature\nFROM sensors.temperature\nGROUP BY month\nORDER BY month",
       "rawQuery": "SELECT\n    toMonth(timestamp) AS month,\n    avg(value) AS monthly_mean_temperature\nFROM sensors.temperature\nGROUP BY month\nORDER BY month",
       "rawSql": "SELECT\n    date,\n    argMax(avg_humidity, insertion_timestamp) AS Humidity\nFROM sensors.humidity_weekly\nWHERE date >= $__fromTime AND date <= $__toTime AND sensor_name = '${sensor_name}'\nGROUP BY date\nORDER BY date",
       "round": "0s"
      }
     ]
    },
    {
     "title": "Min, max and average",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "database": "sensors",
       "dateColDataType": " ",
       "dateTimeColDataType": "timestamp",
       "dateTimeType": "DATETIME64",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n    toDate(timestamp) AS date,\n    avg(value) AS daily_mean_temperature\nFROM sensors.temperature\nGROUP BY date\nORDER BY date\n",
       "rawQuery": "SELECT\n    toDate(timestamp) AS date,\n    avg(value) AS daily_mean_temperature\nFROM sensors.temperature\nGROUP BY date\nORDER BY date",
       "rawSql": "SELECT\n    min(value) as min_humidity,\n    avg(value) AS avg_humidity,\n    max(value) as max_humidity\nFROM sensors.humidity\nwhere sensor_name = '${sensor_name}' and timestamp  >= $__fromTime AND timestamp <= $__toTime\n\n",
       "round": "0s"
      }
     ]
    }
   ]
  },
  {
   "title": "Precipitation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Location",
     "type": "geomap",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 3 },
     "targets": [
      {
       "rawSql": "SELECT distinct sensor_name,\n       'Precipitation' as type,\n       latitude,\n       longitude\nFROM sensors.precipitation\nWHERE sensor_name = '${sensor_name_precipitation}'\n"
      }
     ]
    },
    {
     "title": "Precipitation hourly",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "rawSql": "SELECT\n    date,\n    argMax(avg_precipitation, insertion_timestamp) AS Precipitation\nFROM sensors.precipitation_1h\nWHERE date >= $__fromTime AND date <= $__toTime AND sensor_name = '${sensor_name_precipitation}'\nGROUP BY date\nORDER BY date;"
      }
     ]
    },
    {
     "title": "Daily average",
     "type": "barchart",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "rawSql": "SELECT\n    date,\n    argMax(avg_precipitation, insertion_timestamp) AS Precipitation\nFROM sensors.precipitation_daily\nWHERE date >= $__fromTime AND date <= $__toTime AND sensor_name = '${sensor_name_precipitation}'\nGROUP BY date\nORDER BY date\nLIMIT 30;\n"
      }
     ]
    },
    {
     "title": "Monthly average",
     "type": "barchart",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT\n    toDate(timestamp) AS date,\n    avg(value) AS mean_daily_temperature\nFROM sensors.temperature\nGROUP BY date\nORDER BY date",
       "query": "SELECT\n    toMonth(timestamp) AS month,\n    avg(value) AS monthly_mean_temperature\nFROM sensors.temperature\nGROUP BY month\nORDER BY month",
       "rawQuery": "SELECT\n    toMonth(timestamp) AS month,\n    avg(value) AS monthly_mean_temperature\nFROM sensors.temperature\nGROUP BY month\nORDER BY month",
       "rawSql": "SELECT\n    date,\n    argMax(avg_precipitation, insertion_timestamp) AS Precipitation\nFROM sensors.precipitation_monthly\nWHERE date >= $__fromTime AND date <= $__toTime AND sensor_name = '${sensor_name_precipitation}'\nGROUP BY date\nORDER BY date",
       "round": "0s"
      }
     ]
    },
    {
     "title": "Yearly average",
     "type": "barchart",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT\n    toDate(timestamp) AS date,\n    avg(value) AS mean_daily_temperature\nFROM sensors.temperature\nGROUP BY date\nORDER BY date",
       "query": "SELECT\n    toMonth(timestamp) AS month,\n    avg(value) AS monthly_mean_temperature\nFROM sensors.temperature\nGROUP BY month\nORDER BY month",
       "rawQuery": "SELECT\n    toMonth(timestamp) AS month,\n    avg(value) AS monthly_mean_temperature\nFROM sensors.temperature\nGROUP BY month\nORDER BY month",
       "rawSql": "SELECT\n    date,\n    argMax(avg_precipitation, insertion_timestamp) AS Precipitation\nFROM sensors.precipitation_yearly\nWHERE date >= $__fromTime AND date <= $__toTime AND sensor_name = '${sensor_name_precipitation}'\nGROUP BY date\nORDER BY date",
       "round": "0s"
      }
     ]
    },
    {
     "title": "Min, max and average",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "lengthmm" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "database": "sensors",
       "dateColDataType": " ",
       "dateTimeColDataType": "timestamp",
       "dateTimeType": "DATETIME64",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n    toDate(timestamp) AS date,\n    avg(value) AS daily_mean_temperature\nFROM sensors.temperature\nGROUP BY date\nORDER BY date\n",
       "rawQuery": "SELECT\n    toDate(timestamp) AS date,\n    avg(value) AS daily_mean_temperature\nFROM sensors.temperature\nGROUP BY date\nORDER BY date",
       "rawSql": "SELECT\n    min(value) as min_precipitation,\n    avg(value) AS avg_precipitation,\n    max(value) as max_precipitation\nFROM sensors.precipitation\nwhere sensor_name = '${sensor_name_precipitation}' and timestamp  >= $__fromTime AND timestamp <= $__toTime\n\n",
       "round": "0s"
      }
     ]
    }
   ]
  },
  {
   "title": "River Level",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Location",
     "type": "geomap",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
     "targets": [
      {
       "rawSql": "SELECT distinct sensor_name,\n       'River Level' as type,\n       latitude,\n       longitude\nFROM sensors.river_level\nWHERE sensor_name = '${sensor_name_river_level}'\n"
      }
     ]
    },
    {
     "title": "River Level hourly",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "rawSql": "SELECT\n    date,\n    argMax(avg_river_level, insertion_timestamp) AS River_Level\nFROM sensors.river_level_1h\nWHERE date >= $__fromTime AND date <= $__toTime AND sensor_name = '${sensor_name_river_level}'\nGROUP BY date\nORDER BY date;"
      }
     ]
    },
    {
     "title": "Daily average",
     "type": "barchart",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "rawSql": "SELECT\n    date,\n    argMax(avg_river_level, insertion_timestamp) AS River_level\nFROM sensors.river_level_daily\nWHERE date >= $__fromTime AND date <= $__toTime AND sensor_name = '${sensor_name_river_level}'\nGROUP BY date\nORDER BY date\nLIMIT 30;\n"
      }
     ]
    },
    {
     "title": "Monthly average",
     "type": "barchart",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT\n    toDate(timestamp) AS date,\n    avg(value) AS mean_daily_temperature\nFROM sensors.temperature\nGROUP BY date\nORDER BY date",
       "query": "SELECT\n    toMonth(timestamp) AS month,\n    avg(value) AS monthly_mean_temperature\nFROM sensors.temperature\nGROUP BY month\nORDER BY month",
       "rawQuery": "SELECT\n    toMonth(timestamp) AS month,\n    avg(value) AS monthly_mean_temperature\nFROM sensors.temperature\nGROUP BY month\nORDER BY month",
       "rawSql": "SELECT\n    date,\n    argMax(avg_river_level, insertion_timestamp) AS River_level\nFROM sensors.river_level_monthly\nWHERE date >= $__fromTime AND date <= $__toTime AND sensor_name = '${sensor_name_river_level}'\nGROUP BY date\nORDER BY date",
       "round": "0s"
      }
     ]
    },
    {
     "title": "Yearly average",
     "type": "barchart",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "dateTimeType": "DATETIME",
       "formattedQuery": "SELECT\n    toDate(timestamp) AS date,\n    avg(value) AS mean_daily_temperature\nFROM sensors.temperature\nGROUP BY date\nORDER BY date",
       "query": "SELECT\n    toMonth(timestamp) AS month,\n    avg(value) AS monthly_mean_temperature\nFROM sensors.temperature\nGROUP BY month\nORDER BY month",
       "rawQuery": "SELECT\n    toMonth(timestamp) AS month,\n    avg(value) AS monthly_mean_temperature\nFROM sensors.temperature\nGROUP BY month\nORDER BY month",
       "rawSql": "SELECT\n    date,\n    argMax(avg_river_level, insertion_timestamp) AS River_level\nFROM sensors.river_level_yearly\nWHERE date >= $__fromTime AND date <= $__toTime AND sensor_name = '${sensor_name_river_level}'\nGROUP BY date\nORDER BY date",
       "round": "0s"
      }
     ]
    },
    {
     "title": "Min, max and average",
     "type": "gauge",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "lengthmm" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "database": "sensors",
       "dateColDataType": " ",
       "dateTimeColDataType": "timestamp",
       "dateTimeType": "DATETIME64",
       "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
       "query": "SELECT\n    toDate(timestamp) AS date,\n    avg(value) AS daily_mean_temperature\nFROM sensors.temperature\nGROUP BY date\nORDER BY date\n",
       "rawQuery": "SELECT\n    toDate(timestamp) AS date,\n    avg(value) AS daily_mean_temperature\nFROM sensors.temperature\nGROUP BY date\nORDER BY date",
       "rawSql": "SELECT\n    min(value) as min_river_level,\n    avg(value) AS avg_river_level,\n    max(value) as max_river_level\nFROM sensors.river_level\nwhere sensor_name = '${sensor_name_river_level}' and timestamp  >= $__fromTime AND timestamp <= $__toTime\n\n",
       "round": "0s"
      }
     ]
    }
   ]
  },
  {
   "title": "Air Quality",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Location",
     "type": "geomap",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 5 },
     "targets": [
      {
       "rawSql": "select\n    avg(o3) as avg_o3,\n    avg(no2) as avg_no2,\n    avg(so2) as avg_so2,\n    avg(pm10) as avg_pm10,\n    avg(pm25) as avg_pm25,\n    multiIf(avg_o3 < 50, 1,\n            avg_o3 < 100, 2,\n            avg_o3 < 130, 3,\n            avg_o3 < 240, 4,\n            avg_o3 < 380, 5,\n            6) as o3_level,\n    multiIf(avg_no2 < 40, 1,\n            avg_no2 < 90, 2,\n            avg_no2 < 120, 3,\n            avg_no2 < 230, 4,\n            avg_no2 < 340, 5,\n            6) as no2_level,\n    multiIf(avg_so2 < 100, 1,\n            avg_so2 < 200, 2,\n            avg_so2 < 350, 3,\n            avg_so2 < 500, 4,\n            avg_so2 < 750, 5,\n            6) as so2_level,\n    multiIf(avg_pm10 < 20, 1,\n            avg_pm10 < 40, 2,\n            avg_pm10 < 50, 3,\n            avg_pm10 < 100, 4,\n            avg_pm10 < 150, 5,\n            6) as pm10_level,\n    multiIf(avg_pm25 < 10, 1,\n            avg_pm25 < 20, 2,\n            avg_pm25 < 25, 3,\n            avg_pm25 < 50, 4,\n            avg_pm25 < 75, 5,\n            6) as pm25_level,\n    greatest(o3_level, no2_level, so2_level, pm10_level, pm25_level) as air_quality_index,\n    latitude,\n    longitude,\n    sensor_name\nfrom sensors.air_quality\nwhere timestamp >= $__fromTime and timestamp <= $__toTime\ngroup by sensor_name, latitude, longitude\n"
      }
     ]
    },
    {
     "title": "European Air Quality Index - Real Time",
     "type": "gauge",
     "gridPos": { "h": 9, "w": 5, "x": 0, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n    timestamp,\n    sensor_uuid,\n    GREATEST(\n        multiIf(o3 <= 50, 1, o3 <= 100, 2, o3 <= 130, 3, o3 <= 240, 4, 5),\n        multiIf(no2 <= 40, 1, no2 <= 90, 2, no2 <= 120, 3, no2 <= 230, 4, 5),\n        multiIf(so2 <= 100, 1, so2 <= 200, 2, so2 <= 350, 3, so2 <= 500, 4, 5),\n        multiIf(pm10 <= 20, 1, pm10 <= 40, 2, pm10 <= 50, 3, pm10 <= 100, 4, 5),\n        multiIf(pm25 <= 10, 1, pm25 <= 20, 2, pm25 <= 25, 3, pm25 <= 50, 4, 5)\n    ) AS EAQI\nFROM sensors.air_quality\nORDER BY timestamp, sensor_uuid\n"
      }
     ]
    },
    {
     "title": "Average Pollutants quantity",
     "type": "stat",
     "gridPos": { "h": 9, "w": 19, "x": 5, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "conμgm3" } },
     "targets": [
      {
       "rawSql": "select\n    avg(o3),\n    avg(no2),\n    avg(so2),\n    avg(pm10),\n    avg(pm25)\nfrom sensors.air_quality\nwhere timestamp >= $__fromTime and timestamp <= $__toTime and sensor_name = '${sensor_name_air_quality}'\ngroup by sensor_name, latitude, longitude\n"
      }
     ]
    },
    {
     "title": "Pollutants",
     "type": "barchart",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "conμgm3" } },
     "targets": [
      {
       "rawSql": "select\n    avg(o3) as avg_o3,\n    avg(no2) as avg_no2,\n    avg(so2) as avg_so2,\n    avg(pm10) as avg_pm10,\n    avg(pm25) as avg_pm25,\n    sensor_name\nfrom sensors.air_quality\nwhere timestamp >= $__fromTime and timestamp <= $__toTime and sensor_name = '${sensor_name_air_quality}'\ngroup by sensor_name, latitude, longitude\n"
      }
     ]
    }
   ]
  }
 ]
}