{
 "title": "Raw Data",
 "time": { "from": "2024-05-18T17:12:26.079Z", "to": "2024-05-18T19:12:26.079Z" },
 "templating": {
  "list": [
   {
    "name": "sensor_type",
    "label": "Sensor type",
    "query": "SELECT DISTINCT type FROM sensors;"
   },
   {
    "name": "sensor_name",
    "label": "Sensor",
    "query": "SELECT DISTINCT sensor_name\nFROM sensors\nWHERE type in ($sensor_type)"
   }
  ]
 },
 "panels": [
  { "title": "Sensors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Location",
   "type": "geomap",
   "gridPos": { "h": 12, "w": 20, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "select distinct sensor_name, latitude, longitude\nfrom sensors\nwhere type = 'temperature'\nand type in (${sensor_type})"
    },
    {
     "rawSql": "select distinct sensor_name, latitude, longitude\nfrom sensors\nwhere type = 'traffic'\nand type in (${sensor_type})"
    },
    {
     "rawSql": "select distinct sensor_name, latitude, longitude\nfrom sensors\nwhere type = 'ecological_island'\nand type in (${sensor_type})"
    }
   ]
  },
  { "title": "Dashboards", "type": "dashlist", "gridPos": { "h": 12, "w": 4, "x": 20, "y": 1 } },
  {
   "title": "Sensors",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "select sensor_name, type, max(last_message) as last_message\nfrom sensors\nwhere type in (${sensor_type})\ngroup by sensor_name, type\norder by sensor_name"
    }
   ]
  },
  {
   "title": "Sensors by type",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "with sensors_by_type as (\n    select sensor_name, type, max(last_message) as last_message\n    from sensors\n    group by sensor_name, type\n)\nselect type, count(sensor_name) as count\nfrom sensors_by_type\nwhere type in (${sensor_type})\ngroup by type"
    }
   ]
  },
  { "title": "Raw data", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Temperature",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT sensor_name, value, timestamp\nFROM sensors.temperatures\norder by timestamp desc"
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "rawSql": "SELECT sensor_name, avg_speed, vehicles, timestamp\nFROM sensors.traffic\norder by timestamp desc"
    }
   ]
  },
  {
   "title": "Eco Islands",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "rawSql": "SELECT sensor_name, filling_value, timestamp\nFROM sensors.ecological_island\norder by timestamp desc"
    }
   ]
  }
 ]
}