{
 "title": "Recycling Point",
 "time": { "from": "now/M", "to": "now/M" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "sensor_name",
    "label": "Sensor name",
    "query": "SELECT DISTINCT sensor_name\nFROM sensors.recycling_point\nORDER BY sensor_name"
   }
  ]
 },
 "panels": [
  {
   "title": "Location",
   "type": "geomap",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT sensor_name,\n       'Recycling Point' as type,\n       latitude,\n       longitude\nFROM sensors.recycling_point\nwhere sensor_name = '${sensor_name}'\nGROUP BY sensor_name, latitude, longitude"
    }
   ]
  },
  {
   "title": "History of filling and discharge",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 19, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "select timestamp, filling\nfrom sensors.recycling_point\nwhere timestamp >= $__fromTime and timestamp <= $__toTime\nand sensor_name = '${sensor_name}'\norder by timestamp;"
    }
   ]
  },
  {
   "title": "Real time filling",
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT filling\r\nFROM sensors.recycling_point\r\nWHERE timestamp <= now()\r\nAND sensor_name = '${sensor_name}'\r\nORDER BY timestamp DESC\r\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Total saturation",
   "type": "gauge",
   "description": "This panel shows the cumulative hours that the recycling point has reached its full capacity, rendering it unusable, over a selected period of time.",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "rawSql": "with sequences as (\n    SELECT sensor_name,\n           timestamp,\n           if(neighbor(sensor_uuid, 1, NULL) != sensor_uuid, NULL,\n              neighbor(timestamp, 1, NULL))     as next_timestamp,\n           if(neighbor(sensor_uuid, 1, NULL) != sensor_uuid, NULL,\n              neighbor(filling, 1, NULL)) as next_filling,\n           if(next_filling == 100 and filling == 100, 1, 0) as saturated\n    FROM sensors.recycling_point\n    where timestamp > $__fromTime and timestamp < $__toTime\n),\ngrouped as (\n    select sensor_name,\n           sum(if(saturated = 1, dateDiff('seconds', timestamp, next_timestamp), 0)) as total_seconds\n    from sequences\n    group by sensor_name\n)\nselect *\nfrom grouped\nwhere sensor_name = '${sensor_name}';\n"
    }
   ]
  },
  {
   "title": "Discharge Efficiency Index (DEI)",
   "type": "gauge",
   "description": "Index from 0 to 10 which represent how efficient is the discharge of the selected recycling point. The longer the recycling point stays full without being emptied, the lower the index is and viceversa.",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT avg(if(neighbor(sensor_uuid, -1, NULL) != sensor_uuid, NULL, neighbor(filling, -1, NULL)) AS previous_filling) as avg_filling\nFROM sensors.recycling_point\nwhere filling < previous_filling\nand sensor_name = '${sensor_name}'\nand timestamp > $__fromTime and timestamp < $__toTime"
    }
   ]
  },
  {
   "title": "Filling level percentages by range",
   "type": "barchart",
   "description": "This panel shows the percentage distribution of filling values for the sensor, categorized into three ranges: less than 50% (Low level), from 50% to 80% (Moderate level), more than 80% (High level).",
   "gridPos": { "h": 8, "w": 14, "x": 10, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n    range,\n    (count(*) * 100.0 / total_count) AS percentage,\n    CASE\n        WHEN range = 'High level' THEN 1\n        WHEN range = 'Moderate level' THEN 2\n        WHEN range = 'Low level' THEN 3\n    END AS sort_order\nFROM (\n    SELECT\n        'Low level' AS range,\n        filling\n    FROM sensors.recycling_point\n    WHERE sensor_name = '${sensor_name}' AND filling <= 50\n    and timestamp >= $__fromTime and timestamp <= $__toTime\n    \n    UNION ALL\n\n    SELECT\n        'Moderate level' AS range,\n        filling\n    FROM sensors.recycling_point\n    WHERE sensor_name = '${sensor_name}' AND filling > 50 AND filling <= 80\n    and timestamp >= $__fromTime and timestamp <= $__toTime\n    \n    UNION ALL\n\n    SELECT\n        'High level' AS range,\n        filling\n    FROM sensors.recycling_point\n    WHERE sensor_name = '${sensor_name}' AND filling > 80\n    and timestamp >= $__fromTime and timestamp <= $__toTime\n\n) AS ranges\nCROSS JOIN (\n    SELECT count(*) AS total_count\n    FROM sensors.recycling_point\n    WHERE sensor_name = '${sensor_name}'\n    and timestamp >= $__fromTime and timestamp <= $__toTime\n) AS total\nGROUP BY range, total_count\nORDER BY sort_order;\n"
    }
   ]
  }
 ]
}