{
 "title": "River Level",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "sensor_name",
    "label": "Sensor name",
    "query": "SELECT DISTINCT sensor_name\nFROM sensors.river_level\nORDER BY sensor_name"
   }
  ]
 },
 "panels": [
  {
   "title": "Location",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT distinct sensor_name,\n       'River Level' as type,\n       latitude,\n       longitude\nFROM sensors.river_level\nWHERE sensor_name = '${sensor_name}'\n"
    }
   ]
  },
  {
   "title": "River Level hourly",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 19, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n    date,\n    argMax(avg_river_level, insertion_timestamp) AS River_Level\nFROM sensors.river_level_1h\nWHERE date >= $__fromTime AND date <= $__toTime AND sensor_name = '${sensor_name}'\nGROUP BY date\nORDER BY date;"
    }
   ]
  },
  {
   "title": "Real time",
   "type": "stat",
   "gridPos": { "h": 10, "w": 5, "x": 19, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT value\nFROM sensors.river_level\nWHERE timestamp <= now()\nAND sensor_name = '${sensor_name}'\nORDER BY timestamp DESC\nLIMIT 1"
    }
   ]
  },
  {
   "title": "Hourly average",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT\n    date,\n    argMax(avg_river_level, insertion_timestamp) AS River_Level\nFROM sensors.river_level_1h\nWHERE date >= $__fromTime AND date <= $__toTime AND sensor_name = '${sensor_name}'\nGROUP BY date\nORDER BY date\nLIMIT 30;\n"
    }
   ]
  },
  {
   "title": "Daily average",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "rawSql": "SELECT\n    date,\n    argMax(avg_river_level, insertion_timestamp) AS River_level\nFROM sensors.river_level_daily\nWHERE date >= $__fromTime AND date <= $__toTime AND sensor_name = '${sensor_name}'\nGROUP BY date\nORDER BY date\nLIMIT 30;\n"
    }
   ]
  },
  {
   "title": "Monthly average",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT\n    toDate(timestamp) AS date,\n    avg(value) AS mean_daily_temperature\nFROM sensors.temperatures\nGROUP BY date\nORDER BY date",
     "query": "SELECT\n    toMonth(timestamp) AS month,\n    avg(value) AS monthly_mean_temperature\nFROM sensors.temperatures\nGROUP BY month\nORDER BY month",
     "rawQuery": "SELECT\n    toMonth(timestamp) AS month,\n    avg(value) AS monthly_mean_temperature\nFROM sensors.temperatures\nGROUP BY month\nORDER BY month",
     "rawSql": "SELECT\n    date,\n    argMax(avg_river_level, insertion_timestamp) AS River_level\nFROM sensors.river_level_monthly\nWHERE date >= $__fromTime AND date <= $__toTime AND sensor_name = '${sensor_name}'\nGROUP BY date\nORDER BY date",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Yearly average",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT\n    toDate(timestamp) AS date,\n    avg(value) AS mean_daily_temperature\nFROM sensors.temperatures\nGROUP BY date\nORDER BY date",
     "query": "SELECT\n    toMonth(timestamp) AS month,\n    avg(value) AS monthly_mean_temperature\nFROM sensors.temperatures\nGROUP BY month\nORDER BY month",
     "rawQuery": "SELECT\n    toMonth(timestamp) AS month,\n    avg(value) AS monthly_mean_temperature\nFROM sensors.temperatures\nGROUP BY month\nORDER BY month",
     "rawSql": "SELECT\n    date,\n    argMax(avg_river_level, insertion_timestamp) AS River_level\nFROM sensors.river_level_yearly\nWHERE date >= $__fromTime AND date <= $__toTime AND sensor_name = '${sensor_name}'\nGROUP BY date\nORDER BY date",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Min, max and average",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 18, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "lengthmm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "sensors",
     "dateColDataType": " ",
     "dateTimeColDataType": "timestamp",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    toDate(timestamp) AS date,\n    avg(value) AS daily_mean_temperature\nFROM sensors.temperatures\nGROUP BY date\nORDER BY date\n",
     "rawQuery": "SELECT\n    toDate(timestamp) AS date,\n    avg(value) AS daily_mean_temperature\nFROM sensors.temperatures\nGROUP BY date\nORDER BY date",
     "rawSql": "SELECT\n    min(value) as min_river_level,\n    avg(value) AS avg_river_level,\n    max(value) as max_river_level\nFROM sensors.river_level\nwhere sensor_name = '${sensor_name}' and timestamp  >= $__fromTime AND timestamp <= $__toTime\n\n",
     "round": "0s"
    }
   ]
  }
 ]
}