{
 "title": "Temperature",
 "time": { "from": "now/y", "to": "now/y" },
 "templating": {
  "list": [
   {
    "name": "sensor_name",
    "label": "Sensor name",
    "query": "SELECT DISTINCT sensor_name\nFROM sensors.temperatures\nORDER BY sensor_name"
   }
  ]
 },
 "panels": [
  {
   "title": "Location",
   "type": "geomap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT distinct sensor_name,\n       'Temperature' as type,\n       latitude,\n       longitude\nFROM sensors.temperatures\nWHERE sensor_name = '${sensor_name}'\n"
    }
   ]
  },
  {
   "title": "Real time",
   "type": "stat",
   "gridPos": { "h": 13, "w": 6, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT value\nFROM sensors.temperatures_realtime\nwhere sensor_name = '${sensor_name}'\n"
    }
   ]
  },
  {
   "title": "Time series",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 18, "x": 6, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT value, timestamp\nFROM sensors.temperatures\nwhere sensor_name = '${sensor_name}' and\ntimestamp  >= $__fromTime AND timestamp <= $__toTime "
    }
   ]
  },
  {
   "title": "Monthly average",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT\n    toDate(timestamp) AS date,\n    avg(value) AS mean_daily_temperature\nFROM sensors.temperatures\nGROUP BY date\nORDER BY date",
     "query": "SELECT\n    toMonth(timestamp) AS month,\n    avg(value) AS monthly_mean_temperature\nFROM sensors.temperatures\nGROUP BY month\nORDER BY month",
     "rawQuery": "SELECT\n    toMonth(timestamp) AS month,\n    avg(value) AS monthly_mean_temperature\nFROM sensors.temperatures\nGROUP BY month\nORDER BY month",
     "rawSql": "select date, avg_temperature\nfrom sensors.temperatures_monthly\nwhere (insertion_timestamp, date) in (select max(insertion_timestamp), date\n                                      from sensors.temperatures_monthly\n                                      where sensor_name = '${sensor_name}'\n                                      group by date)\nand date >= $__fromTime and date <= $__toTime\nand sensor_name = '${sensor_name}'\norder by date;\n",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Daily average",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "rawSql": "select date, avg_temperature\nfrom sensors.temperatures_daily\nwhere (insertion_timestamp, date) in (select max(insertion_timestamp), date\n                                      from sensors.temperatures_daily\n                                      where sensor_name = '${sensor_name}'\n                                      group by date)\nand date >= $__fromTime and date <= $__toTime\nand sensor_name = '${sensor_name}'\norder by date;\n"
    }
   ]
  },
  {
   "title": "Min, max and average",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "database": "sensors",
     "dateColDataType": " ",
     "dateTimeColDataType": "timestamp",
     "dateTimeType": "DATETIME64",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    toDate(timestamp) AS date,\n    avg(value) AS daily_mean_temperature\nFROM sensors.temperatures\nGROUP BY date\nORDER BY date\n",
     "rawQuery": "SELECT\n    toDate(timestamp) AS date,\n    avg(value) AS daily_mean_temperature\nFROM sensors.temperatures\nGROUP BY date\nORDER BY date",
     "rawSql": "SELECT\n    min(value) as min_temperature,\n    avg(value) AS avg_temperature,\n    max(value) as max_temperature\nFROM sensors.temperatures\nwhere sensor_name = '${sensor_name}' and timestamp  >= $__fromTime AND timestamp <= $__toTime\n\n",
     "round": "0s"
    }
   ]
  }
 ]
}