{
 "title": "Traffic",
 "time": { "from": "now-2y", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Vehicles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n  timestamp as time, \n  vehicles_per_hour as Vehicles \nFROM sensors.traffic"
    }
   ]
  },
  {
   "title": "Vehicles per months",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT  avg_vehicles_per_hour as Average FROM \"sensors\".\"traff1c\" LIMIT 1000"
    }
   ]
  },
  {
   "title": "Media velocità",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT avg_speed FROM \"sensors\".\"traff1c\" LIMIT 1000"
    }
   ]
  }
 ]
}