{
 "title": "Urban data",
 "time": { "from": "now/y", "to": "now/y" },
 "templating": {
  "list": [
   {
    "name": "group_name_charging",
    "label": "Charging",
    "query": "SELECT DISTINCT group_name\nFROM default.sensors\nWHERE type = 'charging_station'\nand group_name is not null"
   },
   {
    "name": "group_name_parking",
    "label": "Parking",
    "query": "SELECT DISTINCT group_name\nFROM default.sensors\nWHERE type = 'parking'\nand group_name is not null"
   },
   {
    "name": "sensor_name_recycling_point",
    "label": "Recycling Points",
    "query": "SELECT DISTINCT sensor_name\nFROM sensors.recycling_point\nORDER BY sensor_name"
   },
   {
    "name": "sensor_name_traffic",
    "label": "Traffic",
    "query": "SELECT DISTINCT sensor_name\nFROM sensors.traffic\nORDER BY sensor_name"
   }
  ]
 },
 "panels": [
  {
   "title": "Charging",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Real time status",
     "type": "orchestracities-map-panel",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "rawSql": "SELECT latitude, longitude, sensor_name, argMax(kwh_supplied, timestamp) > 0 as status\nfrom sensors.charging_station\nwhere group_name = '${group_name_charging}' and timestamp <= now()\ngroup by latitude, longitude, sensor_name\n"
      }
     ]
    },
    {
     "title": "Total utilization time by charging station",
     "type": "bargauge",
     "gridPos": { "h": 13, "w": 17, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "rawSql": "with sequences as (SELECT sensor_name,\n                          group_name,\n                          timestamp,\n                          kwh_supplied,\n                          if(neighbor(sensor_uuid, 1, NULL) != sensor_uuid, NULL,\n                             neighbor(timestamp, 1, NULL))            as next_timestamp,\n                          dateDiff('seconds', timestamp, next_timestamp) as seconds\n                   FROM sensors.charging_station)\nselect\n    sumIf(seconds, kwh_supplied > 0) as occupied_for,\n    dateDiff('seconds', $__fromTime, $__toTime) as max_time,\n    sensor_name\nfrom sequences\nwhere group_name = '${group_name_charging}'\nand timestamp >= $__fromTime and timestamp <= $__toTime\ngroup by sensor_name\norder by occupied_for desc\n"
      }
     ]
    },
    {
     "title": "Real time occupancy rate",
     "type": "piechart",
     "gridPos": { "h": 13, "w": 7, "x": 17, "y": 15 },
     "targets": [
      {
       "rawSql": "select countIf(occupied) as occupied, count(*) as total, (total - occupied) as free\nfrom (\n         SELECT sensor_name,\n                argMax(kwh_supplied, timestamp) = 0 as occupied\n         FROM sensors.charging_station\n         where group_name = '${group_name_charging}' and timestamp <= now()\n         group by sensor_name\n         );"
      }
     ]
    },
    {
     "title": "Whole park average charging station efficiency and utilization rates",
     "type": "timeseries",
     "description": "This chart shows historical data about charging station efficiency and utilization. Efficiency is calculated dividing the time the charging station was in use by the time the parking lot was occupied. The utilization instead is calculated dividing the charging station was used by the total considered time (which in this case is a day).",
     "gridPos": { "h": 13, "w": 15, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "rawSql": "SELECT group_name, timestamp, avg(efficiency_rate), avg(utilization_rate)\nfrom sensors.charging_efficiency\nwhere group_name = '${group_name_charging}' and timestamp > $__fromTime and timestamp < $__toTime\ngroup by group_name, timestamp"
      }
     ]
    },
    {
     "title": "Whole park average efficiency and utilization",
     "type": "gauge",
     "gridPos": { "h": 13, "w": 9, "x": 15, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT avg(efficiency_rate), avg(utilization_rate)\nfrom sensors.charging_efficiency\nwhere group_name = '${group_name_charging}' \n  and timestamp > $__fromTime \n  and timestamp < $__toTime"
      }
     ]
    },
    {
     "title": "Most/least used/efficienct charging station in the park",
     "type": "canvas",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 41 },
     "targets": [
      {
       "rawSql": "with max_efficiency as (\n    select arrayJoin(sensor_names) as name,\n           avg(efficiency_rate) efficiency\n    from sensors.charging_efficiency\n    where group_name = '${group_name_charging}' and timestamp >= $__fromTime and timestamp <= $__toTime\n    group by name\n    order by efficiency desc\n    limit 1\n),\nmin_efficiency as (\n    select arrayJoin(sensor_names) as name,\n           avg(efficiency_rate) efficiency\n    from sensors.charging_efficiency\n    where group_name = '${group_name_charging}' and timestamp >= $__fromTime and timestamp <= $__toTime\n    group by name\n    order by efficiency\n    limit 1\n),\nmax_utilization as (\n    select arrayJoin(sensor_names) as name,\n           avg(utilization_rate) utilization\n    from sensors.charging_efficiency\n    where group_name = '${group_name_charging}' and timestamp >= $__fromTime and timestamp <= $__toTime\n    group by name\n    order by utilization desc\n    limit 1\n),\nmin_utilization as (\n    select arrayJoin(sensor_names) as name,\n           avg(utilization_rate) utilization\n    from sensors.charging_efficiency\n    where group_name = '${group_name_charging}' and timestamp >= $__fromTime and timestamp <= $__toTime\n    group by name\n    order by utilization\n    limit 1\n)\nselect max_efficiency.name as max_efficiency_sensor,\n       max_efficiency.efficiency as max_efficiency,\n       min_efficiency.name as min_efficiency_sensor,\n       min_efficiency.efficiency as min_efficiency,\n       max_utilization.name as max_utilization_sensor,\n       max_utilization.utilization as max_utilization,\n       min_utilization.name as min_utilization_sensor,\n       min_utilization.utilization as min_utilization\nfrom  max_efficiency, min_efficiency, max_utilization, min_utilization;\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Parking",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Real time status",
     "type": "orchestracities-map-panel",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 69 },
     "targets": [
      {
       "rawSql": "SELECT latitude, longitude, sensor_name, not argMax(is_occupied, timestamp) as status\nfrom sensors.parking\nwhere group_name = '${group_name_parking}' and timestamp <= now()\ngroup by latitude, longitude, sensor_name\n"
      }
     ]
    },
    {
     "title": "Total occupancy time by parking lot",
     "type": "bargauge",
     "gridPos": { "h": 13, "w": 17, "x": 0, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "rawSql": "with sequences as (SELECT sensor_name,\n                          group_name,\n                          timestamp,\n                          is_occupied,\n                          if(neighbor(sensor_uuid, 1, NULL) != sensor_uuid, NULL,\n                             neighbor(timestamp, 1, NULL))            as next_timestamp,\n                          dateDiff('seconds', timestamp, next_timestamp) as seconds\n                   FROM sensors.parking)\nselect\n    sumIf(seconds, is_occupied = 1) as occupied_seconds,\n    dateDiff('seconds', $__fromTime, $__toTime) as max_time,\n    sensor_name\nfrom sequences\nwhere group_name = '${group_name_parking}'\nand timestamp >= $__fromTime and timestamp <= $__toTime\ngroup by sensor_name\norder by occupied_seconds desc\n"
      }
     ]
    },
    {
     "title": "Real time occupancy rate",
     "type": "piechart",
     "gridPos": { "h": 13, "w": 7, "x": 17, "y": 82 },
     "targets": [
      {
       "rawSql": "select countIf(occupied) as occupied, count(*) as total, (total - occupied) as free\nfrom (\n         SELECT sensor_name,\n                argMax(is_occupied, timestamp) as occupied\n         FROM sensors.parking\n         where group_name = '${group_name_parking}' and timestamp <= now()\n         group by sensor_name\n         );"
      }
     ]
    }
   ]
  },
  {
   "title": "Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Location",
     "type": "geomap",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 27 },
     "targets": [
      {
       "rawSql": "SELECT sensor_name,\n       'Traffic' as type,\n       latitude,\n       longitude\nFROM sensors.traffic\nwhere sensor_name = '${sensor_name_traffic}'\nGROUP BY sensor_name, latitude, longitude\n\n"
      }
     ]
    },
    {
     "title": "Avg vehicles per hour",
     "type": "barchart",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
     "targets": [
      {
       "rawSql": "select toHour(date) as hour, argMax(vehicles, insertion_timestamp) as vehicles\nfrom sensors.traffic_1h\nwhere sensor_name = '${sensor_name_traffic}'\nand date >= $__fromTime and date <= $__toTime\ngroup by hour\norder by hour;\n"
      }
     ]
    },
    {
     "title": "Avg speed per hour",
     "type": "barchart",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
     "targets": [
      {
       "rawSql": "select toHour(date) as hour, argMax(speed, insertion_timestamp) \nfrom sensors.traffic_1h\nwhere sensor_name = '${sensor_name_traffic}'\nand date >= $__fromTime and date <= $__toTime\ngroup by hour\norder by hour;\n"
      }
     ]
    }
   ]
  },
  {
   "title": "Recycling Point",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Location",
     "type": "geomap",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
     "targets": [
      {
       "rawSql": "SELECT sensor_name,\n       'Recycling Point' as type,\n       latitude,\n       longitude\nFROM sensors.recycling_point\nwhere sensor_name = '${sensor_name_recycling_point}'\nGROUP BY sensor_name, latitude, longitude"
      }
     ]
    },
    {
     "title": "History of filling and discharge",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
     "targets": [
      {
       "rawSql": "select timestamp, filling\nfrom sensors.recycling_point\nwhere timestamp >= $__fromTime and timestamp <= $__toTime\nand sensor_name = '${sensor_name_recycling_point}'\norder by timestamp;"
      }
     ]
    },
    {
     "title": "Total saturation",
     "type": "gauge",
     "description": "This panel shows the cumulative hours that the recycling point has reached its full capacity, rendering it unusable, over a selected period of time.",
     "gridPos": { "h": 10, "w": 7, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "rawSql": "with sequences as (\n    SELECT sensor_name,\n           timestamp,\n           if(neighbor(sensor_uuid, 1, NULL) != sensor_uuid, NULL,\n              neighbor(timestamp, 1, NULL))     as next_timestamp,\n           if(neighbor(sensor_uuid, 1, NULL) != sensor_uuid, NULL,\n              neighbor(filling, 1, NULL)) as next_filling,\n           if(next_filling == 100 and filling == 100, 1, 0) as saturated\n    FROM sensors.recycling_point\n    where timestamp > $__fromTime and timestamp < $__toTime\n),\ngrouped as (\n    select sensor_name,\n           sum(if(saturated = 1, dateDiff('seconds', timestamp, next_timestamp), 0)) as total_seconds\n    from sequences\n    group by sensor_name\n)\nselect *\nfrom grouped\nwhere sensor_name = '${sensor_name_recycling_point}';\n"
      }
     ]
    },
    {
     "title": "Discharge Efficiency Index (DEI)",
     "type": "gauge",
     "description": "Index from 0 to 10 which represent how efficient is the discharge of the selected recycling point. The longer the recycling point stays full without being emptied, the lower the index is and viceversa.",
     "gridPos": { "h": 9, "w": 7, "x": 8, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "SELECT avg(if(neighbor(sensor_uuid, -1, NULL) != sensor_uuid, NULL, neighbor(filling, -1, NULL)) AS previous_filling) as avg_filling\nFROM sensors.recycling_point\nwhere filling < previous_filling\nand sensor_name = '${sensor_name_recycling_point}'\nand timestamp > $__fromTime and timestamp < $__toTime"
      }
     ]
    },
    {
     "title": "Filling level percentages by range",
     "type": "barchart",
     "description": "This panel shows the percentage distribution of filling values for the sensor, categorized into three ranges: less than 50% (Low level), from 50% to 80% (Moderate level), more than 80% (High level).",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "rawSql": "SELECT\n    range,\n    (count(*) * 100.0 / total_count) AS percentage,\n    CASE\n        WHEN range = 'High level' THEN 1\n        WHEN range = 'Moderate level' THEN 2\n        WHEN range = 'Low level' THEN 3\n    END AS sort_order\nFROM (\n    SELECT\n        'Low level' AS range,\n        filling\n    FROM sensors.recycling_point\n    WHERE sensor_name = '${sensor_name_recycling_point}' AND filling <= 50\n    and timestamp >= $__fromTime and timestamp <= $__toTime\n    \n    UNION ALL\n\n    SELECT\n        'Moderate level' AS range,\n        filling\n    FROM sensors.recycling_point\n    WHERE sensor_name = '${sensor_name}' AND filling > 50 AND filling <= 80\n    and timestamp >= $__fromTime and timestamp <= $__toTime\n    \n    UNION ALL\n\n    SELECT\n        'High level' AS range,\n        filling\n    FROM sensors.recycling_point\n    WHERE sensor_name = '${sensor_name}' AND filling > 80\n    and timestamp >= $__fromTime and timestamp <= $__toTime\n\n) AS ranges\nCROSS JOIN (\n    SELECT count(*) AS total_count\n    FROM sensors.recycling_point\n    WHERE sensor_name = '${sensor_name}'\n    and timestamp >= $__fromTime and timestamp <= $__toTime\n) AS total\nGROUP BY range, total_count\nORDER BY sort_order;\n"
      }
     ]
    }
   ]
  }
 ]
}