[general]
max_workers = 6
log_level = "INFO"

[kafka]
max_block_ms = 1000
topic = "sensors"

[kafka.bootstrap_servers.local] # Configuration for local development
host = "localhost"
port = 9094

[kafka.bootstrap_servers.release] # Configuration for docker-compose
host = "kafka"
port = 9092

# Dates and duration are expressed with ISO8601 standard
[sensors.temperature-sensor-1]
uuid = "b544c389-8fa9-40eb-9b5c-1deaf2383c99"
type = "temperature"
points_spacing = "PT1H" # 1 hour
generation_delay = "PT1S" # 1 second
begin_date = 2023-01-01T00:00:00
latitude = 48.1548976
longitude = 11.2122041

[sensors.traffic-sensor-1]
uuid = "27d1ec68-79f3-440a-854d-8e0d70e50430"
type = "traffic"
points_spacing = "PT1M" # 1 minute
generation_delay = "PT2S" # 2 seconds
latitude = 48.1548976
longitude = 11.2122041
