[general]
max_workers = 6
log_level = "INFO"

[kafka]
max_block_ms = 1000
topic = "sensors"
host = "kafka"
port = 9092

# Dates and duration are expressed with ISO8601 standard
[sensors.temperature-sensor-1]
type = "temperature"
points_spacing = "PT1H" # 1 hour
generation_delay = "PT1S" # 1 second
begin_date = 2023-01-01T00:00:00
latitude = 48.1548976
longitude = 11.2122041

[sensors.traffic-sensor-1]
type = "traffic"
points_spacing = "PT1M" # 1 minute
generation_delay = "PT2S" # 2 seconds
latitude = 48.1548976
longitude = 11.2122041
