networks:
  synccity:
    driver: bridge

services:
  redpanda:
    container_name: redpanda
    command:
      - redpanda
      - start
      - --kafka-addr internal://0.0.0.0:9092,external://0.0.0.0:19092
      - --advertise-kafka-addr internal://redpanda:9092,external://localhost:19092
      - --pandaproxy-addr internal://0.0.0.0:8082,external://0.0.0.0:18082
      - --advertise-pandaproxy-addr internal://redpanda:8082,external://localhost:18082
      - --schema-registry-addr internal://0.0.0.0:8081,external://0.0.0.0:18081
      - --rpc-addr redpanda:33145
      - --advertise-rpc-addr redpanda:33145
      - --mode dev-container
      - --smp 1
      - --overprovisioned
      - --default-log-level=warn
    image: docker.redpanda.com/redpandadata/redpanda:v23.3.11
    volumes:
      - ./volumes/redpanda:/var/lib/redpanda/data
    networks:
      - synccity
    ports:
      - 18081:18081
      - 18082:18082
      - 19092:19092
      - 19644:9644
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "rpk cluster health | awk '/Healthy.*/ {print $2}' | grep -q 'true' || exit 1",
        ]
      interval: 2s
      timeout: 1m
      retries: 12
    profiles: ["test"]

  redpanda_init: # initializes redpanda with topics and schemas which are used by Flink
    container_name: redpanda_init
    build:
      context: ./redpanda
      dockerfile: init.Dockerfile
    networks:
      - synccity
    depends_on:
      redpanda:
        condition: service_healthy
    environment:
      CONFIG_FILEPATH: /etc/redpanda/redpanda.yaml
    command: >
      "
      rpk cluster config -X brokers=http://redpanda:9092 set default_topic_partitions=3;
      create_topic heat_index;
      create_topic humidity;
      create_topic temperature;
      "
    volumes:
      - type: bind
        source: ./redpanda/schemas/
        target: /schemas
      - type: bind
        source: ./redpanda/redpanda-console-config.yaml
        target: /etc/redpanda/redpanda.yaml
    profiles: ["test"]

  redpanda_console:
    container_name: redpanda_console
    image: docker.redpanda.com/redpandadata/console:v2.4.6
    networks:
      - synccity
    ports:
      - 8080:8080
    depends_on:
      redpanda_init:
        condition: service_completed_successfully
    restart: on-failure
    profiles: ["local", "release"]
    environment:
      CONFIG_FILEPATH: /etc/redpanda/redpanda.yaml
    volumes:
      - type: bind
        source: ./redpanda/redpanda-console-config.yaml
        target: /etc/redpanda/redpanda.yaml

  redpanda_connect:
    container_name: redpanda_connect
    image: docker.redpanda.com/redpandadata/connectors:latest
    volumes:
      - ./redpanda/connectors/plugins:/opt/kafka/connect-plugins
      - type: bind
        source: ./redpanda/redpanda-console-config.yaml
        target: /etc/redpanda/redpanda.yaml
    hostname: connect
    ports:
      - "8083:8083"
    depends_on:
      redpanda_init:
        condition: service_completed_successfully
    networks:
      - synccity
    profiles: ["test"]
    environment:
      CONFIG_FILEPATH: /etc/redpanda/redpanda.yaml
      CONNECT_CONFIGURATION: |
        key.converter=java.lang.String
        value.converter=java.lang.String
        plugin.path=/opt/kafka/connect-plugins
        value.converter=io.confluent.connect.avro.AvroConverter
        value.converter.schema.registry.url=http://redpanda:8081
        group.id=connectors-group
        offset.storage.topic=_connectors_offsets
        config.storage.topic=_connectors_configs
        status.storage.topic=_connectors_status
        config.storage.replication.factor=-1
        offset.storage.replication.factor=-1
        status.storage.replication.factor=-1
      CONNECT_BOOTSTRAP_SERVERS: "redpanda:9092"
      CONNECT_GC_LOG_ENABLED: "false"
      CONNECT_HEAP_OPTS: -Xms1G -Xmx1G
      CONNECT_METRICS_ENABLED: "false"
      CONNECT_TLS_ENABLED: "false"
      CONNECT_PLUGIN_PATH: "/opt/kafka/connect-plugins"

  clickhouse:
    image: clickhouse/clickhouse-server:24-alpine
    hostname: clickhouse
    container_name: clickhouse
    ports:
      - "9000:9000"
    healthcheck:
      test: ["CMD", "clickhouse-client", "--query", "SELECT 1"]
      interval: 5s
      timeout: 1m
      retries: 12
    environment:
      CLICKHOUSE_DB: sensors
      CLICKHOUSE_USER: admin
      CLICKHOUSE_PASSWORD: admin
      CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT: 1
    volumes:
      - type: bind
        source: ./clickhouse/timezone.xml
        target: /etc/clickhouse-server/config.d/timezone.xml
      - type: bind
        source: ./clickhouse/init
        target: /docker-entrypoint-initdb.d
    depends_on:
      redpanda:
        condition: service_healthy
    networks:
      - synccity
    profiles: ["test"]
